name: pyright

on: [push, pull_request]

jobs:
  pyright:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.10", "3.9", "3.8", "3.7"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.version }}
          cache: "pip"
      - name: Install pyright
        run: pip install pyright && pip install -r requirements.txt -q
      - name: Run pyright
        run: pyright .
